export enum Names {
  NAVMESH = "navmesh",
}

export enum Events {
  SHOT_FIRED = "SHOT_FIRED",
  UNLOAD_ASSET = "UNLOAD_ASSET",
  SWAP_PLAYER = "SWAP_PLAYER",
  PLACE_FLAG = "PLACE_FLAG",
}

export enum Statuses {
  IN_RANGE = "IN_RANGE",
  LOW_HEALTH = "LOW_HEALTH",
  CAN_RETREAT = "CAN_RETREAT",
  CAN_BERSERK = "CAN_BERSERK",
  REACHED_GOAL = "GOAL",
}

export enum PlayerAnimations {
  IDLE_WHITE = "IDLE_WHITE",
  IDLE_GREEN = "IDLE_GREEN",
  IDLE_BLUE = "IDLE_BLUE",
  IDLE_RED = "IDLE_RED",
  WALK_UP_WHITE = "WALK_UP_WHITE",
  WALK_UP_GREEN = "WALK_UP_GREEN",
  WALK_UP_BLUE = "WALK_UP_BLUE",
  WALK_UP_RED = "WALK_UP_RED",
  WALK_DOWN_WHITE = "WALK_DOWN_WHITE",
  WALK_DOWN_GREEN = "WALK_DOWN_GREEN",
  WALK_DOWN_BLUE = "WALK_DOWN_BLUE",
  WALK_DOWN_RED = "WALK_DOWN_RED",
  WALK_RIGHT_WHITE = "WALK_RIGHT_WHITE",
  WALK_RIGHT_GREEN = "WALK_RIGHT_GREEN",
  WALK_RIGHT_BLUE = "WALK_RIGHT_BLUE",
  WALK_RIGHT_RED = "WALK_RIGHT_RED",
  WALK_LEFT_WHITE = "WALK_LEFT_WHITE",
  WALK_LEFT_GREEN = "WALK_LEFT_GREEN",
  WALK_LEFT_BLUE = "WALK_LEFT_BLUE",
  WALK_LEFT_RED = "WALK_LEFT_RED",
  DAMAGE = "DAMAGE",
}
